# -*- coding: utf-8 -*-
# vim: ft=yaml
#
# Set values specific to:
#   salt['config.get']('os_family') == FreeBSD.
#
# You just need to add the key:values for this `os_family` that differ
# from `defaults.yaml` + `<osarch>.yaml`.
#
# If you do not need to provide defaults via the `os_family` config,
# you can remove this file or provide at least an empty dict, e.g.
# values: {}
---
values:
  identity:
    rootgroup: wheel
  dir:
    etc: /usr/local/etc/prometheus
  pkg:
    component:
      prometheus:
        archive:
          source_hash: 94a63f14baeadab2f17b5ae0bbeda6688e6d06f964ef4e32c2954a0ecf3996a1
      alertmanager:
        archive:
          source_hash: ec171b13976baceace193461f8a1e61021ab9657df5ba45157cd0095aee7d569
      blackbox_exporter:
        archive:
          source_hash: 2b92752decf2cf1883ce4f72301e4f911dab79efbd87db4df23dc9771e53e4af
      consul_exporter:
        archive:
          source_hash: 62e16c2f1acb9bf9411126478caccb5962da203cfb58d8c97f54b9c0add5171c
      graphite_exporter:
        archive:
          source_hash: ff424b923733d8247314353ba4d13a1c4b06450c35f005bfd6c3b6ff60b047fd
      haproxy_exporter:
        archive:
          source_hash: f32d158f9e3314828dc155a30a1f4c858876e1ea8ff543a4000afcbc7e923505
      memcached_exporter:
        archive:
          source_hash: 8fd53b9aede6b78e0530b159ccd0a437cf2f100da1ddc586681f389d804f5f19
      mysqld_exporter:
        archive:
          source_hash: 9bcbbd8b3568818fd4c95d255c6f93c357ea25aed3364d7428f4ff9c89cd489a
      node_exporter: {}
      pushgateway:
        archive:
          source_hash: ebcd21dc25e439eed64559e89cd7da9a94073d5ff321a8a3a4214ac2ebe04e34
      statsd_exporter:
        archive:
          source_hash: f345dff6311501f09bb5b6ba1128e925d504c6325ee97ad91a975f2be0d44da9
  exporters:
    node_exporter:
      textfile_collectors:
        smartmon:
          smartctl: /usr/local/sbin/smartctl
...
