# -*- coding: utf-8 -*-
# vim: ft=yaml
#
# Formula specific configuration of `map.jinja`
---
strategy: recurse
merge_lists: true
values:
  sources:
    - "Y:G@osarch"
    - "Y:G@os_family"
    - "Y:G@init"
    - "C@prometheus:lookup"
    - "C@prometheus"
    - "Y:G@id"
    - "Y:C@roles"
    - "I@prometheus"    # Pillar is disabled for this formula
...
